version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - chat-network

  client:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge
