providers = ["node"]

[variables]
NODE_ENV = "production"

[phases.setup]
cmds = ["cd client"]

[phases.install]
cmds = ["cd client && npm ci"]

[phases.build]
cmds = ["cd client && npm run build"]

[phases.start]
cmd = "cd client && npm run start"
