providers = ["node"]

[variables]
NODE_ENV = "production"

[phases.install]
cmds = ["cd client && npm install"]

[phases.build]
cmds = ["cd client && npm run build"]

[phases.start]
cmd = "cd client && npm run start"
